-- +goose Up
-- +goose StatementBegin

INSERT INTO users (username, password_hash)
VALUES ('admin', '$2b$10$YsSSxmaYpi1zxBt88x6SFOxUWjq1FSJM./mqML8tEp8pKm8Fkodr.'); -- "admin" / пароль "admin123
-- +goose StatementEnd

-- +goose StatementBegin
INSERT INTO goods (title, description, price, old_price, discount, rating, image_url, category, color, is_new, is_hit, hit_rank, new_rank, specs, created_at) VALUES
('Смартфон Apple iPhone 15 256 ГБ розовый', 'Флагманский смартфон Apple с чипом A16 Bionic и двойной камерой 48 Мп.', 102099, NULL, NULL, 5, '/images/goods/iphone-15-pink.png', 'smartphones', 'pink', true, true, 4, 4, '{"Гарантия": "1 год", "Память": "256 ГБ", "Экран": "6.1\" OLED"}'::jsonb, now() - interval '0 minutes'),
('Умный робот-друг Red solution Reddy Air', 'Умный робот-друг с камерой, голосовым управлением и интерактивными играми для всей семьи.', 27990, 31100, 10, 0, '/images/goods/robot-reddy-air.png', 'smart-home', 'white', true, false, 1000, 1, '{"Гарантия": "1 год", "Камера": "1080p", "Батарея": "до 4 часов"}'::jsonb, now() - interval '1 minutes'),
('Часы с GPS трекером Geozon Active Pink (G-W03PNK)', 'Детские умные часы с GPS-трекером, видеозвонками и кнопкой SOS.', 2000, NULL, NULL, 4.8, '/images/goods/geozon-active-pink.png', 'watches', 'pink', true, false, 1000, 2, '{"Гарантия": "1 год", "Экран": "1.4\" IPS", "Защита": "IP67"}'::jsonb, now() - interval '2 minutes'),
('Смарт-часы Samsung Galaxy Watch4 40mm Black (SM-R860N)', 'Смарт-часы с мониторингом сна, пульса и уровня кислорода в крови.', 15199, NULL, NULL, 4, '/images/goods/galaxy-watch4.png', 'watches', 'black', true, false, 1000, 3, '{"Гарантия": "1 год", "Экран": "1.2\" Super AMOLED", "Защита": "5 ATM"}'::jsonb, now() - interval '3 minutes'),
('Смартфон Samsung Galaxy A55 5G 256 ГБ розовый', 'Смартфон среднего класса с поддержкой 5G и ярким AMOLED-экраном 120 Гц.', 43999, NULL, NULL, 4.2, '/images/goods/galaxy-a55-pink.png', 'smartphones', 'pink', false, false, 1000, 1000, '{"Гарантия": "1 год", "Память": "256 ГБ", "Экран": "6.6\" Super AMOLED"}'::jsonb, now() - interval '4 minutes'),
('Умная колонка Яндекс Станция Лайт с Алисой на YaGPT, 5 Вт, розовая', 'Компактная умная колонка с голосовым помощником Алиса.', 4990, NULL, NULL, 3.6, '/images/goods/yandex-station-lite-pink.png', 'speakers', 'pink', false, true, 3, 1000, '{"Гарантия": "1 год", "Мощность": "5 Вт"}'::jsonb, now() - interval '5 minutes'),
('Аппаратный ключ аутентификации Yubico YubiKey Security Key NFC USB-A', 'Аппаратный ключ для двухфакторной аутентификации по стандартам FIDO2 и U2F.', 10590, NULL, NULL, 5, '/images/goods/yubikey-security-key-nfc.png', 'accessories', 'blue', false, true, 2, 1000, '{"Гарантия": "2 года", "Интерфейс": "USB-A, NFC"}'::jsonb, now() - interval '6 minutes'),
('Шлем виртуальной реальности Pico 4 128GB (PC4-128)', 'Автономный VR-шлем с разрешением 4320x2160 и панорамным обзором.', 49990, NULL, NULL, 4.8, '/images/goods/pico-4-128.png', 'vr', 'white', false, true, 1, 1000, '{"Гарантия": "1 год", "Экран": "2160x2160 на глаз", "Память": "128 ГБ"}'::jsonb, now() - interval '7 minutes'),
('Фитнес-браслет HUAWEI Band 8 (ASK-B19) розовый', 'Фитнес-браслет с AMOLED-экраном и мониторингом активности и сна.', 2299, NULL, NULL, 0, '/images/goods/huawei-band-8-pink.png', 'fitness', 'pink', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '8 minutes'),
('Смартфон Samsung Galaxy Z Flip5 8/256GB фиолетовый', 'Смартфон Samsung Galaxy Z Flip5, фиолетовый — девайс со складным корпусом и двумя экранами, что расширяет его возможности.', 94990, NULL, NULL, 5, '/images/goods/galaxy-z-flip5.png', 'smartphones', 'violet', false, true, 5, 1000, '{"Гарантия": "1 год", "Экран": "3.4\"/720x748 Пикс", "Процессор": "Qualcomm Snapdragon 8 Gen 2 1x3.36 ГГц + 2x2.8 ГГц + 2x2.8 ГГц + 3x2.0 ГГц"}'::jsonb, now() - interval '9 minutes'),
('Смартфон Samsung Galaxy A55 5G 256 ГБ фиолетовый', 'Смартфон с поддержкой 5G, камерой 50 Мп и защитой IP67.', 43999, NULL, NULL, 4.5, '/images/goods/galaxy-a55-violet.png', 'smartphones', 'violet', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '10 minutes'),
('Смартфон Samsung Galaxy A55 5G 256 ГБ черный', 'Смартфон с поддержкой 5G, камерой 50 Мп и защитой IP67.', 43999, NULL, NULL, 4.6, '/images/goods/galaxy-a55-black.png', 'smartphones', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '11 minutes'),
('Смартфон Samsung Galaxy A55 5G 256 ГБ белый', 'Смартфон с поддержкой 5G, камерой 50 Мп и защитой IP67.', 43999, NULL, NULL, 4.4, '/images/goods/galaxy-a55-white.png', 'smartphones', 'white', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '12 minutes'),
('Часы с GPS трекером Geozon Active черные (G-W03PNK)', 'Детские умные часы с GPS-трекером, видеозвонками и кнопкой SOS.', 2000, NULL, NULL, 4.7, '/images/goods/geozon-active-black.png', 'watches', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '13 minutes'),
('Часы с GPS трекером Geozon Active синие (G-W03PNK)', 'Детские умные часы с GPS-трекером, видеозвонками и кнопкой SOS.', 2000, NULL, NULL, 4.6, '/images/goods/geozon-active-blue.png', 'watches', 'blue', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '14 minutes'),
('Фитнес-браслет HUAWEI Band 8 (ASK-B19) зеленый', 'Фитнес-браслет с AMOLED-экраном и мониторингом активности и сна.', 2299, NULL, NULL, 4.8, '/images/goods/huawei-band-8-green.png', 'fitness', 'green', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '15 minutes'),
('Фитнес-браслет HUAWEI Band 8 (ASK-B19) черный', 'Фитнес-браслет с AMOLED-экраном и мониторингом активности и сна.', 2299, NULL, NULL, 4.7, '/images/goods/huawei-band-8-black.png', 'fitness', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '16 minutes'),
('Наушники True Wireless HUAWEI FreeBuds SE 2 T0016 белые', 'Беспроводные наушники с автономностью до 40 часов с кейсом.', 2790, NULL, NULL, 4.5, '/images/goods/freebuds-se2-white.png', 'headphones', 'white', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '17 minutes'),
('Наушники True Wireless HUAWEI FreeBuds SE 2 T0016 синие', 'Беспроводные наушники с автономностью до 40 часов с кейсом.', 2790, NULL, NULL, 4.6, '/images/goods/freebuds-se2-blue.png', 'headphones', 'lightblue', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '18 minutes'),
('Наушники True Wireless HUAWEI FreeBuds SE 2 T0016 черные', 'Беспроводные наушники с автономностью до 40 часов с кейсом.', 2790, NULL, NULL, 4.7, '/images/goods/freebuds-se2-black.png', 'headphones', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '19 minutes'),
('Видеокамера для блогера DJI Action 2 Dual-Screen Combo (CP.OS.00000183.01)', 'Компактная магнитная экшн-камера с двумя экранами и съёмкой 4K.', 34990, NULL, NULL, 4.9, '/images/goods/dji-action-2.png', 'accessories', 'gray', false, false, 1000, 1000, '{"Гарантия": "1 год", "Видео": "4K/120"}'::jsonb, now() - interval '20 minutes'),
('Микрофон Barn&Hollis LM01C с разъемом Type-C (УТ000029447)', 'Петличный беспроводной микрофон для смартфонов с разъёмом Type-C.', 1290, NULL, NULL, 4.1, '/images/goods/mic-type-c.png', 'accessories', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '21 minutes'),
('Чехол-подвеска Red Line для Airtag силиконовый с карабином, красный', 'Силиконовый чехол с карабином для метки Apple AirTag.', 490, NULL, NULL, 4.3, '/images/goods/airtag-red.png', 'accessories', 'red', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '22 minutes'),
('Чехол-подвеска Red Line для Airtag силиконовый с карабином, белый', 'Силиконовый чехол с карабином для метки Apple AirTag.', 490, NULL, NULL, 4.2, '/images/goods/airtag-white.png', 'accessories', 'white', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '23 minutes'),
('Чехол-подвеска Red Line для Airtag силиконовый с карабином, серый', 'Силиконовый чехол с карабином для метки Apple AirTag.', 490, NULL, NULL, 4.2, '/images/goods/airtag-gray.png', 'accessories', 'gray', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '24 minutes'),
('Чехол-подвеска Red Line для Airtag силиконовый с карабином, желтый', 'Силиконовый чехол с карабином для метки Apple AirTag.', 490, NULL, NULL, 4.4, '/images/goods/airtag-yellow.png', 'accessories', 'yellow', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '25 minutes'),
('Беспроводная акустика Bunny, серый', 'Портативная Bluetooth-колонка в форме зайца с подсветкой.', 1990, NULL, NULL, 4.3, '/images/goods/speaker-bunny.png', 'speakers', 'gray', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '26 minutes'),
('Беспроводная акустика Самолет, голубой', 'Портативная Bluetooth-колонка с вентилятором-подсветкой.', 2490, NULL, NULL, 4.4, '/images/goods/speaker-plane.png', 'speakers', 'lightblue', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '27 minutes'),
('Беспроводная акустика Мопс, бежевый', 'Портативная Bluetooth-колонка в форме мопса.', 1890, NULL, NULL, 4.5, '/images/goods/speaker-pug.png', 'speakers', 'beige', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '28 minutes'),
('Беспроводная акустика, черный', 'Портативная колонка с RGB-подсветкой и защитой от влаги.', 3290, NULL, NULL, 4.2, '/images/goods/speaker-rgb.png', 'speakers', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '29 minutes'),
('Умная лампа Rubetek RL-3105', 'Умная светодиодная лампа GU10 с управлением цветом через приложение.', 890, NULL, NULL, 4.0, '/images/goods/lamp-rubetek.png', 'smart-home', 'white', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '30 minutes'),
('Аппаратный ключ аутентификации Yubico YubiKey 5 NFC', 'Многопротокольный аппаратный ключ безопасности.', 5990, NULL, NULL, 4.9, '/images/goods/yubikey-5-nfc.png', 'accessories', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '31 minutes'),
('Аппаратный криптокошелек Safepal S1 Pro Hardware Wallet', 'Аппаратный кошелёк для хранения криптоактивов.', 6490, NULL, NULL, 4.4, '/images/goods/safepal-s1-pro.png', 'accessories', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '32 minutes'),
('Очки виртуальной реальности Luazon home VR 2, смартфоны до 6,5"', 'Очки виртуальной реальности для смартфонов с диагональю до 6,5".', 990, NULL, NULL, 3.8, '/images/goods/vr-box-luazon.png', 'vr', 'white', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '33 minutes'),
('Шлем виртуальной реальности Oculus Quest 2 128GB', 'Автономный VR-шлем нового поколения.', 39990, NULL, NULL, 4.8, '/images/goods/oculus-quest-2.png', 'vr', 'white', false, true, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '34 minutes'),
('Умный чемодан-скутер Airwheel SE3 серый', 'Умный чемодан, на котором можно ездить: до 18 км/ч, запас хода 20 км.', 129990, NULL, NULL, 4.6, '/images/goods/airwheel-se3-gray.png', 'scooters', 'gray', false, false, 1000, 1000, '{"Гарантия": "1 год", "Скорость": "до 18 км/ч"}'::jsonb, now() - interval '35 minutes'),
('Умный чемодан-скутер Airwheel SE3 черный', 'Умный чемодан, на котором можно ездить: до 18 км/ч, запас хода 20 км.', 129990, NULL, NULL, 4.7, '/images/goods/airwheel-se3-black.png', 'scooters', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год", "Скорость": "до 18 км/ч"}'::jsonb, now() - interval '36 minutes'),
('Дыхательный тренажер O2in Pro Violet', 'Дыхательный тренажер для релаксации и улучшения самочувствия.', 3490, NULL, NULL, 4.1, '/images/goods/o2in-pro.png', 'accessories', 'pink', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '37 minutes'),
('Внешний аккумулятор 10000mAh, белый', 'Компактный внешний аккумулятор с быстрой зарядкой.', 1290, NULL, NULL, 4.4, '/images/goods/powerbank-white.png', 'accessories', 'white', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '38 minutes'),
('Внешний аккумулятор 10000mAh, черный', 'Компактный внешний аккумулятор с быстрой зарядкой.', 1290, NULL, NULL, 4.5, '/images/goods/powerbank-black.png', 'accessories', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '39 minutes'),
('Bluetooth гарнитура, черный', 'Беспроводная гарнитура с шумоподавлением для звонков.', 5990, NULL, NULL, 4.3, '/images/goods/headset-black.png', 'headphones', 'black', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '40 minutes'),
('Bluetooth гарнитура, серый', 'Беспроводная гарнитура с шумоподавлением для звонков.', 5990, NULL, NULL, 4.2, '/images/goods/headset-gray.png', 'headphones', 'gray', false, false, 1000, 1000, '{"Гарантия": "1 год"}'::jsonb, now() - interval '41 minutes');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM goods;
DELETE FROM users WHERE username = 'admin';
-- +goose StatementEnd
